name: Debug EC2 Deployment

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show working directory and files
        run: |
          echo "Current directory:"
          pwd
          echo "Files in repo:"
          ls -la
