name: Deploy HTML to EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  name: Deploy all HTML pages
  run: |
    sudo cp *.html /var/www/html/
    sudo systemctl restart apache2
