name: Deploy to AWS EC2

on:
  push:
    branches: [ master ]  # or 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: easingthemes/ssh-deploy@v2.2.11
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
          remote-user: ${{ secrets.EC2_USER }}
          server-ip: ${{ secrets.EC2_HOST }}
          remote-path: /var/www/html
          local-path: .
